<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="接口测试脚本集" duration-ms="786" started-at="2020-01-01T06:38:54Z" finished-at="2020-01-01T06:38:55Z">
    <groups>
    </groups>
    <test name="自动化测试用例" duration-ms="786" started-at="2020-01-01T06:38:54Z" finished-at="2020-01-01T06:38:55Z">
      <class name="com.Auto_Test.Case.Test_Case_AutoInterface">
        <test-method status="PASS" signature="read()[pri:0, instance:com.Auto_Test.Case.Test_Case_AutoInterface@7921b0a2]" name="read" is-config="true" duration-ms="15" started-at="2020-01-01T14:38:54Z" finished-at="2020-01-01T14:38:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- read -->
        <test-method status="FAIL" signature="test_case()[pri:0, instance:com.Auto_Test.Case.Test_Case_AutoInterface@7921b0a2]" name="test_case" duration-ms="771" started-at="2020-01-01T14:38:54Z" finished-at="2020-01-01T14:38:55Z">
          <exception class="java.lang.Throwable">
            <full-stacktrace>
              <![CDATA[java.lang.Throwable
	at message : expected [Post] but found [Set] in method : .test_case(Test_Case_AutoInterface:62)
	at com.Auto_Test.Case.Test_Case_AutoInterface.test_case(Test_Case_AutoInterface.java:62)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_case -->
      </class> <!-- com.Auto_Test.Case.Test_Case_AutoInterface -->
    </test> <!-- 自动化测试用例 -->
  </suite> <!-- 接口测试脚本集 -->
</testng-results>
